### PR TITLE
added logo to tab

### PR DESCRIPTION
**Pull request by damwhit**
added little owl icon to tab

### CODE REVIEW

**Comment by damwhit** [comment]
I had to change the file to make the background transparent for the tab

**Comment by weilandia** [comment]
Can't merge this bruh.. You have the access keys in the commit.  Also, we should wait until the other pull merges because it changes a bunch of files

**Comment by weilandia** [comment]
//Will you merge the previous pull?

**Comment by adamhundley** [comment]
hmmm how do we get that .env files out?

**Comment by adamhundley** [comment]
$$$$$$$$$$$$$$

**Pull request merged**
